// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-properties.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_properties_default = defineTool({
  name: "list_properties",
  title: "List properties",
  description: "List Cabinet Pietri properties (id, internal_ref, slug, title, status, price, city). Includes hidden ones only if the caller is admin.",
  inputSchema: {
    include_hidden: z.boolean().optional().describe("Include properties with status 'masque' (admin only)."),
    limit: z.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_hidden, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = client(ctx);
    let q = sb.from("properties").select(
      "id, internal_ref, slug, title, status, price_amount, price_display, price_on_request, city, region, property_type, featured, updated_at"
    ).order("display_order", { ascending: true }).order("created_at", { ascending: false });
    if (!include_hidden) q = q.neq("status", "masque");
    if (limit) q = q.limit(limit);
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { properties: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-property.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_property_default = defineTool2({
  name: "get_property",
  title: "Get property",
  description: "Return the full record for one property, by id, slug, or internal_ref.",
  inputSchema: {
    id: z2.string().uuid().optional(),
    slug: z2.string().optional(),
    internal_ref: z2.string().optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, slug, internal_ref }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    if (!id && !slug && !internal_ref)
      return {
        content: [{ type: "text", text: "Provide id, slug, or internal_ref." }],
        isError: true
      };
    const sb = client2(ctx);
    let q = sb.from("properties").select("*");
    if (id) q = q.eq("id", id);
    else if (slug) q = q.eq("slug", slug);
    else if (internal_ref) q = q.eq("internal_ref", internal_ref);
    const { data, error } = await q.maybeSingle();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return { content: [{ type: "text", text: "Not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { property: data }
    };
  }
});

// src/lib/mcp/tools/search-properties.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_properties_default = defineTool3({
  name: "search_properties",
  title: "Search properties",
  description: "Filter properties by city, property_type, status, min/max price. Returns concise cards.",
  inputSchema: {
    city: z3.string().optional(),
    property_type: z3.enum(["appartement", "maison", "villa", "terrain", "local_commercial", "programme", "autre"]).optional(),
    status: z3.enum(["disponible", "sous_offre", "vendu", "reserve", "masque"]).optional(),
    min_price: z3.number().optional(),
    max_price: z3.number().optional(),
    limit: z3.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ city, property_type, status, min_price, max_price, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = client3(ctx);
    let q = sb.from("properties").select(
      "id, internal_ref, slug, title, status, price_amount, price_display, city, property_type, area_m2, bedrooms"
    );
    if (city) q = q.ilike("city", `%${city}%`);
    if (property_type) q = q.eq("property_type", property_type);
    if (status) q = q.eq("status", status);
    else q = q.neq("status", "masque");
    if (min_price != null) q = q.gte("price_amount", min_price);
    if (max_price != null) q = q.lte("price_amount", max_price);
    q = q.limit(limit ?? 30);
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { results: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/update-property-status.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^4.4.3";
function client4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function isAdmin(ctx) {
  const sb = client4(ctx);
  const { data } = await sb.from("user_roles").select("role").eq("user_id", ctx.getUserId()).eq("role", "admin").maybeSingle();
  return !!data;
}
var update_property_status_default = defineTool4({
  name: "update_property_status",
  title: "Update property status",
  description: "Change a property status to disponible, sous_offre, reserve, vendu, or masque. Admin only.",
  inputSchema: {
    id: z4.string().uuid(),
    status: z4.enum(["disponible", "sous_offre", "reserve", "vendu", "masque"])
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ id, status }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    if (!await isAdmin(ctx))
      return { content: [{ type: "text", text: "Admin role required" }], isError: true };
    const sb = client4(ctx);
    const { data, error } = await sb.from("properties").update({ status }).eq("id", id).select("id, title, status").maybeSingle();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Status updated: ${JSON.stringify(data)}` }],
      structuredContent: { property: data }
    };
  }
});

// src/lib/mcp/tools/update-property-media.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^4.4.3";
function client5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function isAdmin2(ctx) {
  const sb = client5(ctx);
  const { data } = await sb.from("user_roles").select("role").eq("user_id", ctx.getUserId()).eq("role", "admin").maybeSingle();
  return !!data;
}
var update_property_media_default = defineTool5({
  name: "update_property_media",
  title: "Update property media",
  description: "Update video / virtual tour fields on a property (video_url, video_url_2, drone_video_url, hero_video_url, virtual_tour_url, virtual_tour_iframe, matterport_id, show_video, show_virtual_tour). Only provided fields are updated. Admin only.",
  inputSchema: {
    id: z5.string().uuid(),
    video_url: z5.string().nullable().optional(),
    video_url_2: z5.string().nullable().optional(),
    drone_video_url: z5.string().nullable().optional(),
    hero_video_url: z5.string().nullable().optional(),
    virtual_tour_url: z5.string().nullable().optional(),
    virtual_tour_iframe: z5.string().nullable().optional(),
    matterport_id: z5.string().nullable().optional(),
    show_video: z5.boolean().optional(),
    show_virtual_tour: z5.boolean().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    if (!await isAdmin2(ctx))
      return { content: [{ type: "text", text: "Admin role required" }], isError: true };
    const { id, ...patch } = input;
    const cleanPatch = Object.fromEntries(Object.entries(patch).filter(([, v]) => v !== void 0));
    if (Object.keys(cleanPatch).length === 0)
      return { content: [{ type: "text", text: "No fields to update" }], isError: true };
    const sb = client5(ctx);
    const { data, error } = await sb.from("properties").update(cleanPatch).eq("id", id).select("id, title, video_url, video_url_2, drone_video_url, virtual_tour_url, show_video, show_virtual_tour").maybeSingle();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Media updated: ${JSON.stringify(data)}` }],
      structuredContent: { property: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pkwxoqvswcotqaatdrtq";
var mcp_default = defineMcp({
  name: "cabinet-pietri-mcp",
  title: "Cabinet Pietri Immobilier",
  version: "0.1.0",
  instructions: "Outils pour g\xE9rer et interroger les biens du site Cabinet Pietri Immobilier. Utilisez list_properties et search_properties pour explorer, get_property pour les d\xE9tails, update_property_status et update_property_media pour modifier (admin requis).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_properties_default, get_property_default, search_properties_default, update_property_status_default, update_property_media_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
